language: node_js
node_js:
- '6'
before_script:
- npm install -g webpack
- npm install -g codecov
before_deploy:
- npm run deploy
deploy:
  provider: heroku
  api_key:
   secure: "f6sCNIkhpAcE3VdqpHFP5Vpx5nOPKFSpyXgypzGp/LIWZPZJ1JqeS8NruIIfjYXSHr4ib2NMn7goVXONZe2ycGciZbuOoghFVJyaiqZHoeUXCjcvBWghRiLs8erHGjUf/MLHaCwlW0/SYvvjbX4YoEocSify/NHwas6sAagVMFuD9GurLZ/rkE0yzwyGQ824PSeYG6ybiGUCQO6WemsyFiVMZS/OCO8Pm3ANHWWsg8QFXT/a7GaFAfek2Wk4udJa42YSRZDPeTc9zrEk9FOCaZAWuiTRGu64Bb9yZDLb/9O4RaZXSWySzPGT0/rCemwrGtjmVIZd3BC+ftXqmx6vZysoQ4uI5nBWNAmDIOXxJ/6N4IZkN3RrLf+LVtwZjylvsh4GZ6RdqAw+vMJ34ihCj0/k4Js84mBsfyAaA1Hm2EDLD7ZTHhqHT1TzyTsF4XUtsEA/c4IrdauQp1wc4yIR0722KhT5eFdq1ZszNk2qiFXz2y9lOaHF2T6rKmxj9ys8+a12f3Su9XLzG3+p03Kb7h4xFHJ1zMHasyrznn48zC5ZFGBpBWUhFSS77hEj6zCKdrt8BkbCm550ei0b0EhH55Df7QrQPHxRxmA2TIyG6FXZTkyHZXtyIXd3S4vEfAJCsH1mfASqQbEDDbn4twaAa1IZdE95adyald3cOoj9J2M="
  app: ksiazekm-jaa-ui
  on:
    repo: ksiazekm/JAlgoArena-UI
